experiment:
  name: "baseline_with_rejection"
  alias: "experiment_01"  # Unique alias for the experiment
  base_root: "/home/ran/afeka/computer-vision"  # Base directory for all experiment outputs
  rejection_gate_threshold: 0.5

input:
  folder: "/home/ran/datasets/pcam"

rejection_models:
  - name: "random_rejector"
    path: "./models/random_rejector.py"
    weight: 0.3  # Weight for this model's rejection decision
    
  - name: "dummy_rejector"
    path: "./models/dummy_rejector.py"
    weight: 0.7  # Weight for this model's rejection decision

baseline_model:
  name: "baseline_cnn"
  path: "./models/baseline_cnn.pth"  # Trained model weights
