experiment:
  name: "baseline_no_rejection"
  alias: "experiment_baseline_no_rejection"  # Unique alias for the experiment
  base_root: "/home/ran/afeka/computer-vision"  # Base directory for all experiment outputs
  batch_size: 1
  rejection_gate_threshold: 1.0

input:
  folder: "/home/ran/datasets/pcam"
  reduce_to_center: false

rejection_models:
  - name: "random_rejector"
    path: "./models/random_rejector.py"
    weight: 0.3  # Weight for this model's rejection decision
    
  - name: "dummy_rejector"
    path: "./models/dummy_rejector.py"
    weight: 0.7  # Weight for this model's rejection decision

baseline_model:
  name: "baseline_cnn"
  path: "/home/ran/afeka/computer-vision/baseline_cnn_trained.pth"  # Trained model weights
