experiment:
  name: "baseline_svm"
  alias: "experiment_02"  # Unique alias for the experiment
  base_root: "/home/ran/afeka/computer-vision"  # Base directory for all experiment outputs
  rejection_gate_threshold: 0.5
  description: "one class svm"

input:
  folder: "/home/ran/datasets/pcam"
  reduce_to_center: false
  batch_size: 32
  sample_size: 0.02
  split: "test"

rejection_models:
  - name: "one-class-svm"
    path: "/home/ran/afeka/computer-vision/models/one-class-svm.joblib"
    weight: 1  # Weight for this model's rejection decision

baseline_model:
  original_results: "/home/ran/afeka/computer-vision/experiment_baseline_no_rejection/results.parquet"
  original_metrics: "/home/ran/afeka/computer-vision/experiment_baseline_no_rejection/metrics.json"

