experiment:
  name: "baseline_mahalanobis"
  alias: "experiment_01"  # Unique alias for the experiment
  base_root: "/home/linuxu/afeka/computer-vision"  # Base directory for all experiment outputs
  rejection_gate_threshold: 0.5
  description: "mahalanobis"

input:
  folder: "/home/ran/datasets/pcam"
  batch_size: 128
  sample_size: 0.33

rejection_models:
- name: "mahalanobis"
  weight: 1
  policy:
    save_path: "/home/linuxu/afeka/computer-vision/models/mahalanobis.joblib"
    enabled: true
  

baseline_model:
  original_results: "/home/linuxu/afeka/computer-vision/experiment_baseline_no_rejection/results.parquet"
  original_metrics: "/home/linuxu/afeka/computer-vision/experiment_baseline_no_rejection/metrics.json"

