experiment:
  name: "baseline_with_rejection"
  alias: "experiment_01"  # Unique alias for the experiment
  base_root: "/home/linuxu/afeka/computer-vision"  # Base directory for all experiment outputs
  batch_size: 1
  rejection_gate_threshold: 0.5

input:
  folder: "/home/linuxu/datasets/pcam"
  reduce_to_center: false

rejection_models:
  - name: "lof"
    path: "/home/linuxu/afeka/computer-vision/models/lof.joblib"
    weight: 0.5  # Weight for this model's rejection decision
    
  - name: "isolation_forest"
    path: "/home/linuxu/afeka/computer-vision/models/isolation_forest.joblib"
    weight: 0.5  # Weight for this model's rejection decision

baseline_model:
  name: "baseline_cnn"
  path: "/home/linuxu/afeka/computer-vision/models/baseline_cnn.pth"  # Trained model weights
  enabled: false
