input:
    folder: "/home/linuxu/datasets/pcam"
    batch_size: 64
    sample_size: 0.3

rejection_models:
  enabled: true
  models:
  - name: "mahalanobis"
    weight: 1
    policy:
      save_path: "/home/linuxu/afeka/computer-vision/models/mahalanobis.joblib"
  - name: "knn"
    weight: 1
    policy:
      n_neighbors: 10
      save_path: "/home/linuxu/afeka/computer-vision/models/knn.joblib"
  - name: "margin"
    weight: 1
    policy:
      boundary: 0.5
  
    
baseline_model:
  name: "baseline_cnn"
  train:
    enabled: false
    learning_rate: 0.001
    epochs: 20
    save_path: "/home/linuxu/afeka/computer-vision/models/baseline_cnn.pth"
