input:
  folder: "/home/ran/datasets/pcam"

rejection_models:
  - name: "lof"
    save_path: "/home/ran/afeka/computer-vision/models/lof.joblib"
    n_neighbors: 20
    contamination: 0.1
    enabled: true
    
  - name: "isolation forest"
    save_path: "/home/ran/afeka/computer-vision/models/isolation_forest.joblib"
    n_estimators: 100
    max_samples: 256
    contamination: 0.1
    enabled: true
    
baseline_model:
  name: "baseline_cnn"
  save_path: "/home/ran/afeka/computer-vision/models/baseline_cnn.pth"
  enabled: false
