rejection_models:
- name: "lof"
  input:
    folder: "/home/ran/datasets/pcam"
    reduce_to_center: true
    batch_size: 64
    sample_size: 0.15
  policy:
    save_path: "/home/ran/afeka/computer-vision/models/lof.joblib"
    n_neighbors: 12
    contamination: 0.005
    enabled: true
    
- name: "isolation_forest"
  input:
    folder: "/home/ran/datasets/pcam"
    reduce_to_center: true
    batch_size: 32
    sample_size: 0.8
  policy:
    save_path: "/home/ran/afeka/computer-vision/models/isolation_forest.joblib"
    max_samples: 32768
    n_estimators: 300
    contamination: 0.005
    enabled: true
    
baseline_model:
  name: "baseline_cnn"
  save_path: "/home/ran/afeka/computer-vision/models/baseline_cnn.pth"
  enabled: false
