rejection_models:
- name: "one-class-svm"
  input:
    folder: "/home/ran/datasets/pcam"
    reduce_to_center: false
    batch_size: 64
    sample_size: 0.01
  policy:
    save_path: "/home/ran/afeka/computer-vision/models/one-class-svm.joblib"
    enabled: true
    nu: 0.1
    kernel: "rbf"
    gamma: "scale"

- name: "lof"
  input:
    folder: "/home/ran/datasets/pcam"
    reduce_to_center: false
    batch_size: 64
    sample_size: 0.05
  policy:
    save_path: "/home/ran/afeka/computer-vision/models/lof.joblib"
    n_neighbors: 12
    contamination: 0.005
    enabled: true
    
- name: "isolation_forest"
  input:
    folder: "/home/ran/datasets/pcam"
    reduce_to_center: false
    batch_size: 32
    sample_size: 0.10
  policy:
    save_path: "/home/ran/afeka/computer-vision/models/isolation_forest.joblib"
    max_samples: 32768
    n_estimators: 300
    contamination: 0.005
    enabled: true
    
baseline_model:
  name: "baseline_cnn"
  save_path: "/home/ran/afeka/computer-vision/models/baseline_cnn.pth"
  enabled: false
